version: "3.7"
services:
  web1:
    build: ./quote_gen
    container_name: gen
    ports:
      - "5000:5000"
  web2:
    build: ./quote_disp
    restart: always
    ports:
      - "5001-5010:5001"
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - web1